Repository googleapis/nodejs-bigquery, pull requests merged in 2019-04, with the labels that each got.

#385 fix(ts): provide complete and correct types
  package.json
  src/dataset.ts
  src/index.ts
  src/job.ts
  src/table.ts
  src/types.d.ts
  system-test/bigquery.ts
  test/dataset.ts
  test/index.ts
  test/table.ts
Labels: :rotating_light:, automerge, cla: yes

#397 feat(geo): add support for geography
  src/index.ts
  src/table.ts
  system-test/bigquery.ts
  test/index.ts
Labels: :rotating_light:, automerge, cla: yes

#404 Release @google-cloud/bigquery v3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#407 fix(types): correct interface
  src/table.ts
Labels: automerge, cla: yes

#412 fix: remove teeny-request as a direct dependency
  package.json
  src/dataset.ts
  src/index.ts
  src/job.ts
  src/table.ts
Labels: cla: yes

#409 refactor: use execSync for tests
  package.json
  samples/package.json
  samples/test/datasets.test.js
  samples/test/queries.test.js
  samples/test/quickstart.test.js
  samples/test/tables.test.js
Labels: cla: yes

#414 refactor(ts): cast arrified rows
  src/table.ts
Labels: cla: yes

#411 docs(samples): adds queryParamsArrays, queryParamsStructs, queryParam…
  .cloud-repo-tools.json
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/queryParamsArrays.js
  samples/queryParamsStructs.js
  samples/queryParamsTimestamps.js
  samples/test/queries.test.js
Labels: :rotating_light:, cla: yes

#415 refactor(docs): add new sample links to README.md
  README.md
  samples/README.md
Labels: :rotating_light:, cla: yes

#421 refactor: drop `autoCreate` in table.insert() in favor of `schema`
  src/table.ts
  test/table.ts
Labels: cla: yes

#422 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
