Repository googleapis/nodejs-bigquery, pull requests merged in 2019-05, with the labels that each got.

#420 chore: cleanup repo metadata and remove unused files
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  samples/system-test/.eslintrc.yml
  synth.metadata
Labels: cla: yes

#423 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#424 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#425 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#430 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#432 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#429 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#431 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#438 fix(table): allow for TableSchema to be used
  src/table.ts
Labels: cla: yes

#439 fix: correctly encode nested struct/array params
  src/index.ts
  test/index.ts
Labels: cla: yes

#441 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#447 docs(samples): reference the dataset that's actually used
  samples/query.js
Labels: cla: yes

#448 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#449 feat(model): dataset model support
  package.json
  src/dataset.ts
  src/index.ts
  src/model.ts
  src/types.d.ts
  system-test/bigquery.ts
  test/dataset.ts
  test/model.ts
Labels: cla: yes

#452 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#453 chore: remove unused request types package
  package.json
  src/table.ts
Labels: cla: yes

#457 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#455 feat: accept apiEndpoint override
  package.json
  src/index.ts
  src/table.ts
  test/index.ts
  test/table.ts
Labels: cla: yes

#461 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#451 chore: release 4.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#462 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#467 fix: correct name in .repo-metadata.json
  .repo-metadata.json
Labels: cla: yes

#465 fix(job): remove job instance from request params
  src/job.ts
  test/job.ts
Labels: cla: yes

#468 chore: release 4.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#460 docs(samples): adds get, delete, list, update model samples
  samples/deleteModel.js
  samples/getModel.js
  samples/listModels.js
  samples/listModelsStreaming.js
  samples/package.json
  samples/test/models.test.js
  samples/updateModel.js
Labels: cla: yes

#469 feat(table): support all sourceFormat types
  src/table.ts
  test/table.ts
Labels: cla: yes

#472 fix(deps): bump the min version on all dependencies
  package.json
Labels: cla: yes
