Repository googleapis/nodejs-bigquery, pull requests merged in 2019-06, with the labels that each got.

#474 docs: include full list of samples in the README
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#475 build: remove unused clang format
  .clang-format
  src/table.ts
Labels: automerge, cla: yes

#477 fix: link to new googleapis.dev docs
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#478 chore: release 4.1.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#476 refactor(samples): adds rows variable
  samples/insertRowsAsStream.js
Labels: cla: yes

#479 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
Labels: cla: yes

#480 chore: release 4.1.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#485 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#486 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#489 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
