Repository googleapis/nodejs-bigquery, pull requests merged in 2019-02, with the labels that each got.

#342 feat: throw errors for missing resource ids
  src/dataset.ts
  src/index.ts
  test/dataset.ts
  test/index.ts
Labels: cla: yes

#344 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#349 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#350 docs: update contributing path in README
  README.md
Labels: cla: yes

#351 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#352 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#358 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#354 build: use linkinator for docs test
  package.json
Labels: cla: yes

#345 test: skip installation test if GOOGLE_CLOUD_TESTS_IN_VPCSC is passed
  system-test/install.ts
Labels: :rotating_light:, cla: yes

#363 chore: make test prefix unique per run
  system-test/bigquery.ts
Labels: cla: yes, type: cleanup

#364 Revert "chore: make test prefix unique per run"
  system-test/bigquery.ts
Labels: cla: yes
