Repository googleapis/nodejs-bigquery, pull requests merged in 2019-03, with the labels that each got.

#365 fix(types): move JobLoadMetadata writeDisposition
  src/table.ts
Labels: cla: yes

#366 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#369 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#370 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#368 refactor(samples): split samples into their own files
  samples/bigquery_create_dataset.js
  samples/bigquery_delete_dataset.js
  samples/bigquery_list_datasets.js
  samples/datasets.js
  samples/test/datasets.test.js
Labels: cla: yes

#374 fix: update samples and docs to match rubric
  .cloud-repo-tools.json
  README.md
  package.json
  samples/README.md
  samples/createDataset.js
  samples/deleteDataset.js
  samples/listDatasets.js
  samples/quickstart.js
  samples/test/datasets.test.js
  system-test/bigquery.ts
Labels: cla: yes

#377 testing: remove nextQuery assertion
  system-test/bigquery.ts
Labels: cla: yes

#376 docs(table): link to upstream limit docs
  src/table.ts
Labels: cla: yes

#378 Release @google-cloud/bigquery v2.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#382 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#381 docs(samples): adds queryParamsNamed and queryParamsPositional
  .cloud-repo-tools.json
  README.md
  samples/README.md
  samples/queryParamsNamed.js
  samples/queryParamsPositional.js
  samples/test/queries.test.js
Labels: automerge, cla: yes

#386 refactor(samples): fix loadJSONFromGCSTruncate wrong function
  README.md
  samples/README.md
  samples/loadJSONFromGCSTruncate.js
  samples/loadOrcFromGCSTruncate.js
Labels: cla: yes

#390 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#394 fix(tests): update TIMESTAMP param tests
  system-test/bigquery.ts
Labels: cla: yes

#387 fix(job): check for `errorResult` when polling jobs
  src/job.ts
  test/job.ts
Labels: cla: yes

#393 fix: correctly encode nested custom date/time parameters
  src/index.ts
  test/index.ts
Labels: cla: yes

#401 refactor(samples): add main() function wrappers to samples
  samples/browseRows.js
  samples/copyTable.js
  samples/createDataset.js
  samples/createTable.js
  samples/deleteDataset.js
  samples/deleteTable.js
  samples/extractTableToGCS.js
  samples/insertRowsAsStream.js
  samples/listDatasets.js
  samples/listTables.js
  samples/loadCSVFromGCS.js
  samples/loadCSVFromGCSAutodetect.js
  samples/loadCSVFromGCSTruncate.js
  samples/loadJSONFromGCS.js
  samples/loadJSONFromGCSAutodetect.js
  samples/loadJSONFromGCSTruncate.js
  samples/loadLocalFile.js
  samples/loadOrcFromGCSTruncate.js
  samples/loadParquetFromGCSTruncate.js
  samples/loadTableGCSORC.js
  samples/loadTableGCSParquet.js
  samples/query.js
  samples/queryDisableCache.js
  samples/queryParamsNamed.js
  samples/queryParamsPositional.js
  samples/queryStackOverflow.js
  samples/quickstart.js
Labels: automerge, cla: yes
