Repository googleapis/nodejs-bigquery, pull requests merged in 2020-08, with the labels that each got.

#832 feat: model extract
  src/model.ts
  system-test/bigquery.ts
  test/model.ts
Labels: cla: yes

#749 doc: docs for defaultDataset
  src/bigquery.ts
Labels: cla: yes

#837 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#839 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#841 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#830 docs(samples): adds routine and user agent samples
  samples/createRoutine.js
  samples/createRoutineDDL.js
  samples/deleteRoutine.js
  samples/getRoutine.js
  samples/listRoutines.js
  samples/setUserAgent.js
  samples/test/authViewTutorial.test.js
  samples/test/clients.test.js
  samples/test/datasets.test.js
  samples/test/models.test.js
  samples/test/queries.test.js
  samples/test/routines.test.js
  samples/test/tables.test.js
  samples/updateRoutine.js
Labels: cla: yes

#845 docs: update list of samples available on the README
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#846 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#844 docs(samples): adds Create model sample
  samples/createModel.js
  samples/test/models.test.js
Labels: api: bigquery, cla: yes

#848 build: move system and samples test from Node 10 to Node 12
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#851 docs: update list of samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#852 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
