Repository googleapis/nodejs-bigquery, pull requests merged in 2020-10, with the labels that each got.

#867 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#868 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#876 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#878 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#882 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#877 fix: Detect Geography type during parameterized query
  src/bigquery.ts
  test/bigquery.ts
Labels: api: bigquery, cla: yes

#873 feat: optionally wrap INT64 in BigQueryInt or provide a custom INT64 value type cast options
  src/bigquery.ts
  src/index.ts
  src/job.ts
  src/table.ts
  test/bigquery.ts
  test/job.ts
  test/table.ts
Labels: api: bigquery, cla: yes
