Repository googleapis/nodejs-bigquery, pull requests merged in 2020-04, with the labels that each got.

#665 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#667 feat: update types.d.ts
  .eslintrc.json
  .github/workflows/ci.yaml
  .prettierrc.js
  src/types.d.ts
  synth.metadata
Labels: cla: yes

#668 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#669 fix: apache license URL (#468)
  .prettierrc.js
  synth.metadata
Labels: automerge, cla: yes

#672 chore(deps): upgrade to gts v2
  .eslintignore
  .eslintrc.yml
  .prettierignore
  .prettierrc
  benchmark/bench.ts
  package.json
  samples/addColumnLoadAppend.js
  samples/queryLegacy.js
  samples/queryLegacyLargeResults.js
  samples/queryParamsStructs.js
  samples/queryParamsTimestamps.js
  samples/test/datasets.test.js
  samples/test/jobs.test.js
  samples/test/models.test.js
  samples/test/queries.test.js
  samples/test/tables.test.js
  src/bigquery.ts
  src/dataset.ts
  src/job.ts
  src/table.ts
  src/types.d.ts
  system-test/bigquery.ts
  system-test/fixtures/kitchen/src/index.ts
  system-test/install.ts
  test/bigquery.ts
  test/dataset.ts
  test/job.ts
  test/model.ts
  test/table.ts
  tslint.json
Labels: cla: yes

#673 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#674 test(samples): test all samples and not just tables
  samples/test/tables.test.js
Labels: cla: yes

#589 fix(table): add retries for insert partial failures
  package.json
  src/table.ts
  system-test/bigquery.ts
  test/table.ts
Labels: cla: yes, do not merge

#677 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#678 fix(docs): link for job configuration load
  src/table.ts
Labels: cla: yes

#679 build: use codecov's action, now that it's authless
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes

#680 fix: add types for hasDrift and seasonalPeriods
  src/types.d.ts
  synth.metadata
Labels: cla: yes

#681 fix(types): drop changes for drift and seasonal
  src/types.d.ts
  synth.metadata
Labels: cla: yes

#683 feat: improved types
  src/types.d.ts
  synth.metadata
Labels: cla: yes

#685 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes
