Repository googleapis/nodejs-bigquery, pull requests merged in 2020-06, with the labels that each got.

#709 fix(docs): configuration.copy link
  src/table.ts
Labels: cla: yes

#711 chore(query): updates error message and docs for provided param types
  src/bigquery.ts
  test/bigquery.ts
Labels: cla: yes

#713 docs(samples): updates test resource naming to improve traceability
  samples/test/datasets.test.js
  samples/test/jobs.test.js
  samples/test/models.test.js
  samples/test/queries.test.js
  samples/test/quickstart.test.js
  samples/test/tables.test.js
Labels: cla: yes

#671 feat(userAgent): allow for optional user agent to be provided
  package.json
  src/bigquery.ts
Labels: cla: yes, do not merge

#714 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#747 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#748 fix: load job to a different project ID
  src/table.ts
  test/table.ts
Labels: automerge, cla: yes

#752 tests(system): adds check for creationTime
  system-test/bigquery.ts
Labels: cla: yes

#712 fix: selectedFields on getRows not working correctly
  src/bigquery.ts
  src/table.ts
  test/table.ts
Labels: cla: yes

#754 test: refactors system test deleteDatasets()
  system-test/bigquery.ts
Labels: cla: yes

#798 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#797 docs(samples): adds sample for providing query parameter types
  samples/queryParamsNamedTypes.js
  samples/queryParamsPositionalTypes.js
  samples/test/queries.test.js
Labels: cla: yes

#803 docs: populate additional samples
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#801 fix: blunderbuss config
  .github/blunderbuss.yml
Labels: cla: yes

#804 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
