Repository googleapis/nodejs-bigquery, pull requests merged in 2020-07, with the labels that each got.

#809 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#807 fix: add tests for Routine
  src/routine.ts
  test/routine.ts
Labels: api: bigquery, cla: yes

#811 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#755 chore: correct BigQuery product name in repo-metadata.json
  .repo-metadata.json
Labels: automerge, cla: yes

#814 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#817 docs: update createQueryJob documentation
  src/bigquery.ts
Labels: cla: yes

#815 docs: update product title
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#816 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#813 feat: detect param type if not in provided types
  src/bigquery.ts
  test/bigquery.ts
Labels: cla: yes

#822 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#827 fix: add string type for query types
  src/bigquery.ts
Labels: cla: yes

#828 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#824 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#821 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#829 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#831 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#833 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
