Repository googleapis/nodejs-bigquery, pull requests merged in 2020-05, with the labels that each got.

#688 chore: add Blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#692 test: provide hint that calledWith_ exists on stubbed objects
  test/bigquery.ts
  test/dataset.ts
  test/job.ts
  test/table.ts
Labels: cla: yes

#693 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#698 fix: drop dependency on string-format-obj
  package.json
  src/bigquery.ts
  src/table.ts
Labels: cla: yes

#699 refactor: reduce usage of extend
  src/bigquery.ts
  src/dataset.ts
  src/job.ts
  src/table.ts
  test/bigquery.ts
  test/dataset.ts
  test/job.ts
  test/model.ts
  test/table.ts
Labels: cla: yes

#701 fix(docs): correct createTablePartitioned sample argument
  samples/createTablePartitioned.js
  samples/test/tables.test.js
Labels: cla: yes

#687 docs(samples): Adds Samples
  samples/authViewTutorial.js
  samples/createTableRangePartitioned.js
  samples/insertingDataTypes.js
  samples/queryExternalGCSPerm.js
  samples/relaxColumnQueryAppend.js
  samples/test/authViewTutorial.test.js
  samples/test/queries.test.js
  samples/test/tables.test.js
Labels: cla: yes

#705 docs: adds new samples to docs
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
