Repository googleapis/nodejs-bigquery, pull requests merged in 2020-12, with the labels that each got.

#895 docs(samples): Update table.getRows and dataset access samples
  samples/browseRows.js
  samples/browseTable.js
  samples/queryPagination.js
  samples/test/jobs.test.js
  samples/test/tables.test.js
  samples/updateDatasetAccess.js
Labels: api: bigquery, cla: yes, samples

#902 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: api: bigquery, cla: yes, context: none

#900 fix: update returned Job with API-determined location in getMetadata
  src/job.ts
  test/job.ts
Labels: api: bigquery, cla: yes

#908 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full
