Repository googleapis/nodejs-bigquery, pull requests merged in 2021-04, with the labels that each got.

#946 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#950 build: Add generate-files-bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#952 chore(deps): drop dependency on pReflect
  package.json
  test/table.ts
Labels: api: bigquery, cla: yes
