Repository googleapis/nodejs-bigquery, pull requests merged in 2021-08, with the labels that each got.

#981 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
  README.md
Labels: api: bigquery, automerge, cla: yes

#986 fix(build): migrate to using main branch
  .github/.OwlBot.lock.yaml
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  samples/README.md
Labels: cla: yes, api: bigquery

#990 docs(samples): update test to run auth-user-sample test
  samples/test/auth.test.js
Labels: cla: yes, api: bigquery, samples

#988 docs: Update type annotations
  src/bigquery.ts
  src/dataset.ts
  src/job.ts
  src/model.ts
  src/routine.ts
  src/table.ts
Labels: cla: yes, api: bigquery

#991 feat: add support for loading Firestore export file
  src/table.ts
  test/table.ts
Labels: cla: yes, api: bigquery

#1000 chore: add string type to Table.query & Dataset.query
  src/dataset.ts
  src/table.ts
  test/table.ts
Labels: cla: yes, api: bigquery
