Repository googleapis/nodejs-bigquery, pull requests merged in 2023-09, with the labels that each got.

#1282 fix: updating type for test blocking dependency updates
  test/rowQueue.ts
Labels: automerge, api: bigquery, size: xs

#1271 feat: re-exporting types for google-common
  src/bigquery.ts
  src/index.ts
Labels: api: bigquery, size: xs

#1273 Avoid TypeError if resp is undefined
  src/rowQueue.ts
Labels: automerge, api: bigquery, size: xs

#1284 fix: updated types from API discovery doc
  src/types.d.ts
Labels: api: bigquery, size: m
